language: python
python:
  - "3.5"
  - "3.6"
install:
  pip install -r requirements-dev.txt;
script:
  - flake8 .
  - coverage run -m pytest
after_success:
  - codecov
notifications:
  email:
    - felipe.gomes.ferreira@gmail.com